cc_binary(
    name = "data_main",
    srcs = ["data_main.cc"],
    deps = [
        "//include:data_library",
    ],
)

cc_binary(
    name = "predict_main",
    srcs = ["predict_main.cc"],
    deps = [
        "//include:data_library",
    ],
)

cc_binary(
    name = "train_main",
    srcs = ["train_main.cc"],
    deps = [
        "//include:data_library",
    ],
)
